### PR TITLE
Changed types and import library name

### PR DESCRIPTION
**Pull request by konikvranik**
to be usable with esp8266 on case sensitive file system

### CODE REVIEW

**Review by ESikich — CHANGES_REQUESTED** [review]
Can you explain the case sensitive issue?  Is there any reason to change the values in the Color struct to int32_t?  It only needs to hold a value from 0-255.

**Comment by konikvranik** [comment]
Hi Eric,

changes was made because original code is not compilable with ESP8266 platform. So for wider compatibility.

Here is output from compiler:
`.piolibdeps/RGBLEDBlender_ID1223/src/RGBLEDBlender.h:26:21: fatal error: arduino.h: No such file or directory`

**Comment by ESikich** [comment]
What specifically is the compatibility issue?  From my understanding, the difference between with Arduino and the ESP is that ints are 16 bits in Arduino but 32 for the ESP.  This shouldn't be an issue as ints aren't used in this code at all.  What problems are you running into?  Can you post the compilation error messages?

**Comment by ESikich** [comment]
I see now.  It looks like you just need to re-pull this repository.  This was already fixed in commit df470fc218e54c0d69692e3709e77a3773ad9d48.

Thanks,
Erik

**Comment by konikvranik** [comment]
> I see now. It looks like you just need to re-pull this repository. This was already fixed in commit [df470fc](https://github.com/ESikich/RGBLEDBlender/commit/df470fc218e54c0d69692e3709e77a3773ad9d48).
> 
> Thanks,
> Erik

Good to know. But in platformio libraries there are still old buggy version. Can you, please, rerelease fixed library?

**Comment by ESikich** [comment]
Hm.  I've never used that site before.  It looks like they have a crawler
that looks at GitHub repos.  I'll try changing the version number and I'll
see if that works.  Might take a while though.

-Erik

**Comment by konikvranik** [comment]
Version 1.1.4 is compiling fine.
Thank you :-)

**Comment by konikvranik** [comment]
Type sizes are not the main issue. There are only warnings.

The main problem is small "a" in `#include "arduino.h"`. It leads into compilation failure: `.piolibdeps/RGBLEDBlender_ID1223/src/RGBLEDBlender.h:26:21: fatal error: arduino.h: No such file or directory`

**Pull request closed without merging**
